In [1]:
import pandas as pd  # Import pandas for DataFrame operations
import numpy as np   # Import numpy for numerical operations

In [2]:
# Create Employee DataFrame using dictionary
employee_data = {                                                                       # Dictionary to store employee data
    "ID": ["A001","A002","A003","A004","A005"],                                         # Employee IDs
    "Name": ["John Alter","Alice Luxumberg","Tom Sabestine","Nina Adgra","Amy Johny"],  # Full names
    "Gender": ["M","F","M","F","F"],                                                    # Gender column
    "City": ["Paris","London","Berlin","Newyork","Madrid"],                             # City column
    "Age": [25,27,29,31,30]                                                             # Age column
}

employee_df = pd.DataFrame(employee_data)                                               # Convert dictionary to DataFrame
employee_df.to_csv("Employee.csv", index=False)                                         # Save DataFrame as CSV file

In [3]:
# Create Seniority DataFrame using dictionary
seniority_data = {                                                                      # Dictionary for seniority data
    "ID": ["A001","A002","A003","A004","A005"],                                         # Employee IDs
    "Designation Level": [2,2,3,2,3]                                                    # Designation levels
}

seniority_df = pd.DataFrame(seniority_data)                                             # Convert dictionary to DataFrame
seniority_df.to_csv("Seniority.csv", index=False)                                       # Save as CSV

In [4]:
# Create Project DataFrame using dictionary
project_data = {                                                                        # Dictionary for project data
    "ID": ["A001","A002","A003","A004","A005","A002","A005","A003","A001","A003",       # Employee IDs
           "A001","A004","A004","A005"],                                                
    "Project": ["Project 1","Project 2","Project 3","Project 4","Project 5",            #Project
                "Project 6","Project 7","Project 8","Project 9","Project 10",
                "Project 11","Project 12","Project 13","Project 14"],
    "Cost": [1002000,2000000,4500000,5500000,np.nan,680000,400000,350000,               #Project Cost
             np.nan,300000,2000000,1000000,3000000,200000],
    "Status": ["Finished","Ongoing","Finished","Ongoing","Finished"                     #Project Status
               ,"Failed","Finished","Failed",
               "Ongoing","Finished","Failed","Ongoing","Finished","Finished"]
}

project_df = pd.DataFrame(project_data)                                                  # Convert dictionary to DataFrame
project_df.to_csv("Project.csv", index=False)                                            # Save as CSV

In [5]:
                 #----------------Task 2 : Replace the missing values by running average.-------------
# Read Project CSV file
project_df = pd.read_csv("Project.csv")                                                   # Load project data

# Convert Cost column to float (so decimals are handled properly)
project_df["Cost"] = project_df["Cost"].astype(float)

# Initialize variables
running_total = 0.0                                                                       # Store cumulative total as float
count = 0                                                                                 # Count non-missing values

# Loop through each row
for i in range(len(project_df)):                                                          # Iterate row by row
    
    if not pd.isna(project_df.loc[i, "Cost"]):                                            # If Cost is NOT missing
        running_total += project_df.loc[i, "Cost"]                                        # Add to running total
        count += 1                                                                        # Increase count
        
    else:                                                                                 # If Cost is missing
        average = running_total / count                                                   # Calculate running average
        project_df.loc[i, "Cost"] = round(average, 2)                                     # Replace with 2 decimal value
# Remove scientific notation display
pd.options.display.float_format = '{:.2f}'.format

# Save updated CSV
project_df.to_csv("Project.csv", index=False)

In [6]:
                                     # Output of Task 2 : Replace the missing values by running average.
project_df

      ID     Project       Cost    Status
0   A001   Project 1 1002000.00  Finished
1   A002   Project 2 2000000.00   Ongoing
2   A003   Project 3 4500000.00  Finished
3   A004   Project 4 5500000.00   Ongoing
4   A005   Project 5 3250500.00  Finished
5   A002   Project 6  680000.00    Failed
6   A005   Project 7  400000.00  Finished
7   A003   Project 8  350000.00    Failed
8   A001   Project 9 2061714.29   Ongoing
9   A003  Project 10  300000.00  Finished
10  A001  Project 11 2000000.00    Failed
11  A004  Project 12 1000000.00   Ongoing
12  A004  Project 13 3000000.00  Finished
13  A005  Project 14  200000.00  Finished

In [7]:
                         #--------------------Task 3 – Split Name Column-----------------------------------
# Read Employee CSV
employee_df = pd.read_csv("Employee.csv")   # Load employee data

# Split Name column into First and Last name
employee_df[["First Name","Last Name"]] = employee_df["Name"].str.split(" ", expand=True)

# Drop old Name column
employee_df.drop("Name", axis=1, inplace=True)

employee_df.to_csv("Employee.csv", index=False)  # Save updated file

In [8]:
                                     #Output of Task 3 – Split Name Column
employee_df

     ID Gender     City  Age First Name  Last Name
0  A001      M    Paris   25       John      Alter
1  A002      F   London   27      Alice  Luxumberg
2  A003      M   Berlin   29        Tom  Sabestine
3  A004      F  Newyork   31       Nina      Adgra
4  A005      F   Madrid   30        Amy      Johny

In [9]:
                                     #---------------------- Task 4: Join All DataFrames--------------------------
# Read all CSV files
employee_df = pd.read_csv("Employee.csv")                                     # Employee data
seniority_df = pd.read_csv("Seniority.csv")                                   # Seniority data
project_df = pd.read_csv("Project.csv")                                       # Project data

# Merge Employee and Seniority
final_df = pd.merge(employee_df, seniority_df, on="ID")

# Merge with Project
final_df = pd.merge(final_df, project_df, on="ID")

final_df.to_csv("Final.csv", index=False)                                     # Save final dataframe

In [10]:
                                                #Output of Task 4: Join All DataFrames
final_df

,ID,Gender,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status
0,A001,M,Paris,25,John,Alter,2,Project 1,1002000.00,Finished
1,A001,M,Paris,25,John,Alter,2,Project 9,2061714.29,Ongoing
2,A001,M,Paris,25,John,Alter,2,Project 11,2000000.00,Failed
3,A002,F,London,27,Alice,Luxumberg,2,Project 2,2000000.00,Ongoing
4,A002,F,London,27,Alice,Luxumberg,2,Project 6,680000.00,Failed
5,A003,M,Berlin,29,Tom,Sabestine,3,Project 3,4500000.00,Finished
6,A003,M,Berlin,29,Tom,Sabestine,3,Project 8,350000.00,Failed
7,A003,M,Berlin,29,Tom,Sabestine,3,Project 10,300000.00,Finished
8,A004,F,Newyork,31,Nina,Adgra,2,Project 4,5500000.00,Ongoing
9,A004,F,Newyork,31,Nina,Adgra,2,Project 12,1000000.00,Ongoing
10,A004,F,Newyork,31,Nina,Adgra,2,Project 13,3000000.00,Finished
11,A005,F,Madrid,30,Amy,Johny,3,Project 5,3250500.00,Finished
12,A005,F,Madrid,30,Amy,Johny,3,Project 7,400000.00,Finished
13,A005,F,Madrid,30,Amy,Johny,3,Project 14,200000.00,Finished

In [11]:
                            #-----------------Task 5 – Add Bonus Column (5% if Finished)---------------
# Add Bonus column with condition
final_df["Bonus"] = np.where(final_df["Status"]=="Finished",
                             final_df["Cost"]*0.05,
                             0)

final_df.to_csv("Final.csv", index=False)

In [12]:
                                        #Output of Task 5 – Add Bonus Column (5% if Finished)
final_df

,ID,Gender,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,M,Paris,25,John,Alter,2,Project 1,1002000.00,Finished,50100.00
1,A001,M,Paris,25,John,Alter,2,Project 9,2061714.29,Ongoing,0.00
2,A001,M,Paris,25,John,Alter,2,Project 11,2000000.00,Failed,0.00
3,A002,F,London,27,Alice,Luxumberg,2,Project 2,2000000.00,Ongoing,0.00
4,A002,F,London,27,Alice,Luxumberg,2,Project 6,680000.00,Failed,0.00
5,A003,M,Berlin,29,Tom,Sabestine,3,Project 3,4500000.00,Finished,225000.00
6,A003,M,Berlin,29,Tom,Sabestine,3,Project 8,350000.00,Failed,0.00
7,A003,M,Berlin,29,Tom,Sabestine,3,Project 10,300000.00,Finished,15000.00
8,A004,F,Newyork,31,Nina,Adgra,2,Project 4,5500000.00,Ongoing,0.00
9,A004,F,Newyork,31,Nina,Adgra,2,Project 12,1000000.00,Ongoing,0.00
10,A004,F,Newyork,31,Nina,Adgra,2,Project 13,3000000.00,Finished,150000.00
11,A005,F,Madrid,30,Amy,Johny,3,Project 5,3250500.00,Finished,162525.00
12,A005,F,Madrid,30,Amy,Johny,3,Project 7,400000.00,Finished,20000.00
13,A005,F,Madrid,30,Amy,Johny,3,Project 14,200000.00,Finished,10000.00

In [13]:
                    #-----------Task 6 Demote for Failed Projects and Delete employees with designation level 4---------
# Reduce designation level by 1 where status is Failed
final_df.loc[final_df["Status"]=="Failed","Designation Level"] -= 1

# Delete employees with designation level > 4
final_df = final_df[final_df["Designation Level"] <= 4]

final_df.to_csv("Final.csv", index=False)

In [14]:
                    #Output of Task 6 Demote for Failed Projects and Delete employees with designation level 4
final_df

,ID,Gender,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,M,Paris,25,John,Alter,2,Project 1,1002000.00,Finished,50100.00
1,A001,M,Paris,25,John,Alter,2,Project 9,2061714.29,Ongoing,0.00
2,A001,M,Paris,25,John,Alter,1,Project 11,2000000.00,Failed,0.00
3,A002,F,London,27,Alice,Luxumberg,2,Project 2,2000000.00,Ongoing,0.00
4,A002,F,London,27,Alice,Luxumberg,1,Project 6,680000.00,Failed,0.00
5,A003,M,Berlin,29,Tom,Sabestine,3,Project 3,4500000.00,Finished,225000.00
6,A003,M,Berlin,29,Tom,Sabestine,2,Project 8,350000.00,Failed,0.00
7,A003,M,Berlin,29,Tom,Sabestine,3,Project 10,300000.00,Finished,15000.00
8,A004,F,Newyork,31,Nina,Adgra,2,Project 4,5500000.00,Ongoing,0.00
9,A004,F,Newyork,31,Nina,Adgra,2,Project 12,1000000.00,Ongoing,0.00
10,A004,F,Newyork,31,Nina,Adgra,2,Project 13,3000000.00,Finished,150000.00
11,A005,F,Madrid,30,Amy,Johny,3,Project 5,3250500.00,Finished,162525.00
12,A005,F,Madrid,30,Amy,Johny,3,Project 7,400000.00,Finished,20000.00
13,A005,F,Madrid,30,Amy,Johny,3,Project 14,200000.00,Finished,10000.00

In [15]:
                             #--------------- Task 7 – Add Mr./Mrs. and Drop Gender----------------
# Add prefix based on gender
final_df["First Name"] = np.where(final_df["Gender"]=="M",
                                  "Mr. " + final_df["First Name"],
                                  "Mrs. " + final_df["First Name"])

# Drop Gender column
final_df.drop("Gender", axis=1, inplace=True)

final_df.to_csv("Final.csv", index=False)

In [16]:
                            #Output of Task 7 – Add Mr./Mrs. and Drop Gender
final_df

,ID,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,Paris,25,Mr. John,Alter,2,Project 1,1002000.00,Finished,50100.00
1,A001,Paris,25,Mr. John,Alter,2,Project 9,2061714.29,Ongoing,0.00
2,A001,Paris,25,Mr. John,Alter,1,Project 11,2000000.00,Failed,0.00
3,A002,London,27,Mrs. Alice,Luxumberg,2,Project 2,2000000.00,Ongoing,0.00
4,A002,London,27,Mrs. Alice,Luxumberg,1,Project 6,680000.00,Failed,0.00
5,A003,Berlin,29,Mr. Tom,Sabestine,3,Project 3,4500000.00,Finished,225000.00
6,A003,Berlin,29,Mr. Tom,Sabestine,2,Project 8,350000.00,Failed,0.00
7,A003,Berlin,29,Mr. Tom,Sabestine,3,Project 10,300000.00,Finished,15000.00
8,A004,Newyork,31,Mrs. Nina,Adgra,2,Project 4,5500000.00,Ongoing,0.00
9,A004,Newyork,31,Mrs. Nina,Adgra,2,Project 12,1000000.00,Ongoing,0.00
10,A004,Newyork,31,Mrs. Nina,Adgra,2,Project 13,3000000.00,Finished,150000.00
11,A005,Madrid,30,Mrs. Amy,Johny,3,Project 5,3250500.00,Finished,162525.00
12,A005,Madrid,30,Mrs. Amy,Johny,3,Project 7,400000.00,Finished,20000.00
13,A005,Madrid,30,Mrs. Amy,Johny,3,Project 14,200000.00,Finished,10000.00

In [17]:
               #---------------Task 8 – Promote Designation Level by 1 if Age > 29 (Using IF Condition)---------------

# Loop through each row of dataframe
for i in range(len(final_df)):              # Iterate through each row index
    
    if final_df.loc[i, "Age"] > 29:         # Check if Age is greater than 29
        
        final_df.loc[i, "Designation Level"] += 1   # Promote by increase level number by 1
        
        if final_df.loc[i, "Designation Level"] < 1:  # Check if level goes below 1
            final_df.loc[i, "Designation Level"] = 1  # Keep minimum level as 1

# Save updated dataframe
final_df.to_csv("Final.csv", index=False)   # Save changes back to CSV

In [18]:
                          #Output of Task 8 – Promote Designation Level by 1 if Age > 29 (Using IF Condition)
final_df

,ID,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,Paris,25,Mr. John,Alter,2,Project 1,1002000.00,Finished,50100.00
1,A001,Paris,25,Mr. John,Alter,2,Project 9,2061714.29,Ongoing,0.00
2,A001,Paris,25,Mr. John,Alter,1,Project 11,2000000.00,Failed,0.00
3,A002,London,27,Mrs. Alice,Luxumberg,2,Project 2,2000000.00,Ongoing,0.00
4,A002,London,27,Mrs. Alice,Luxumberg,1,Project 6,680000.00,Failed,0.00
5,A003,Berlin,29,Mr. Tom,Sabestine,3,Project 3,4500000.00,Finished,225000.00
6,A003,Berlin,29,Mr. Tom,Sabestine,2,Project 8,350000.00,Failed,0.00
7,A003,Berlin,29,Mr. Tom,Sabestine,3,Project 10,300000.00,Finished,15000.00
8,A004,Newyork,31,Mrs. Nina,Adgra,3,Project 4,5500000.00,Ongoing,0.00
9,A004,Newyork,31,Mrs. Nina,Adgra,3,Project 12,1000000.00,Ongoing,0.00
10,A004,Newyork,31,Mrs. Nina,Adgra,3,Project 13,3000000.00,Finished,150000.00
11,A005,Madrid,30,Mrs. Amy,Johny,4,Project 5,3250500.00,Finished,162525.00
12,A005,Madrid,30,Mrs. Amy,Johny,4,Project 7,400000.00,Finished,20000.00
13,A005,Madrid,30,Mrs. Amy,Johny,4,Project 14,200000.00,Finished,10000.00

In [19]:
                           #--------------Task 9 – Total Project Cost per Employee------------------
# Group by ID and First Name and sum Cost
total_proj_cost = final_df.groupby(["ID","First Name"])["Cost"].sum().reset_index()

# Rename column
total_proj_cost.rename(columns={"Cost":"Total Cost"}, inplace=True)

total_proj_cost.to_csv("TotalProjCost.csv", index=False)

In [20]:
                                 #Output of Task 9 – Total Project Cost per Employee
total_proj_cost

     ID  First Name  Total Cost
0  A001    Mr. John  5063714.29
1  A002  Mrs. Alice  2680000.00
2  A003     Mr. Tom  5150000.00
3  A004   Mrs. Nina  9500000.00
4  A005    Mrs. Amy  3850500.00

In [21]:
                    #----------------Task 10 – Print Employees Where City Contains "o"-------------------
# Filter rows where city contains letter 'o'
filtered_df = final_df[final_df["City"].str.contains("o", case=False)]

In [22]:
                      #Output of Task 10 – Print Employees Where City Contains "o"
filtered_df

,ID,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
3,A002,London,27,Mrs. Alice,Luxumberg,2,Project 2,2000000.00,Ongoing,0.00
4,A002,London,27,Mrs. Alice,Luxumberg,1,Project 6,680000.00,Failed,0.00
8,A004,Newyork,31,Mrs. Nina,Adgra,3,Project 4,5500000.00,Ongoing,0.00
9,A004,Newyork,31,Mrs. Nina,Adgra,3,Project 12,1000000.00,Ongoing,0.00
10,A004,Newyork,31,Mrs. Nina,Adgra,3,Project 13,3000000.00,Finished,150000.00